package output

import (
	"fmt"
	"html/template"
	"os"
	"time"

	"github.com/gocisse/sdwan-triage/pkg/models"
)

// GenerateDebugHTML generates a simplified HTML report for debugging purposes
func GenerateDebugHTML(report *models.TriageReport, filename string, pcapFile string) error {
	// Create a simple debug HTML template
	debugTemplate := `<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Debug Report - {{.PCAPFile}}</title>
    <style>
        body { font-family: monospace; margin: 20px; background: #1a1a2e; color: #eee; }
        h1, h2, h3 { color: #00d9ff; }
        .section { background: #16213e; padding: 15px; margin: 10px 0; border-radius: 8px; }
        .count { color: #00ff88; font-weight: bold; }
        .warning { color: #ffaa00; }
        .error { color: #ff4444; }
        pre { background: #0f0f23; padding: 10px; overflow-x: auto; border-radius: 4px; }
        table { border-collapse: collapse; width: 100%; margin: 10px 0; }
        th, td { border: 1px solid #333; padding: 8px; text-align: left; }
        th { background: #1a1a4e; }
        tr:nth-child(even) { background: #1a1a3e; }
    </style>
</head>
<body>
    <h1>🔧 Debug Report</h1>
    <p>Generated: {{.Timestamp}}</p>
    <p>PCAP File: {{.PCAPFile}}</p>

    <div class="section">
        <h2>📊 Summary Statistics</h2>
        <ul>
            <li>Total Bytes: <span class="count">{{.TotalBytes}}</span></li>
            <li>DNS Anomalies: <span class="count">{{.DNSAnomalyCount}}</span></li>
            <li>TCP Retransmissions: <span class="count">{{.TCPRetransmissionCount}}</span></li>
            <li>Failed Handshakes: <span class="count">{{.FailedHandshakeCount}}</span></li>
            <li>TLS Certificates: <span class="count">{{.TLSCertCount}}</span></li>
            <li>ARP Conflicts: <span class="count">{{.ARPConflictCount}}</span></li>
            <li>HTTP Errors: <span class="count">{{.HTTPErrorCount}}</span></li>
            <li>Traffic Flows: <span class="count">{{.TrafficFlowCount}}</span></li>
        </ul>
    </div>

    <div class="section">
        <h2>🔒 Security Analysis</h2>
        <ul>
            <li>DDoS Findings: <span class="count">{{.DDoSCount}}</span></li>
            <li>Port Scan Findings: <span class="count">{{.PortScanCount}}</span></li>
            <li>IOC Findings: <span class="count">{{.IOCCount}}</span></li>
            <li>TLS Security Issues: <span class="count">{{.TLSSecurityCount}}</span></li>
        </ul>
    </div>

    <div class="section">
        <h2>🌐 Network Analysis</h2>
        <ul>
            <li>ICMP Findings: <span class="count">{{.ICMPCount}}</span></li>
            <li>Tunnel Findings: <span class="count">{{.TunnelCount}}</span></li>
            <li>SD-WAN Vendors: <span class="count">{{.SDWANVendorCount}}</span></li>
            <li>BGP Hijack Indicators: <span class="count">{{.BGPIndicatorCount}}</span></li>
        </ul>
    </div>

    <div class="section">
        <h2>📋 Risk Assessment</h2>
        <ul>
            <li>Risk Score: <span class="count">{{.RiskScore}}</span></li>
            <li>Risk Level: <span class="{{if eq .RiskLevel "Critical"}}error{{else if eq .RiskLevel "High"}}warning{{else}}count{{end}}">{{.RiskLevel}}</span></li>
            <li>Top Issue: {{.TopIssue}}</li>
        </ul>
    </div>

    {{if .DNSAnomalies}}
    <div class="section">
        <h2>🔍 DNS Anomalies (First 20)</h2>
        <table>
            <tr><th>Query</th><th>Answer IP</th><th>Server IP</th><th>Reason</th></tr>
            {{range .DNSAnomalies}}
            <tr><td>{{.Query}}</td><td>{{.AnswerIP}}</td><td>{{.ServerIP}}</td><td>{{.Reason}}</td></tr>
            {{end}}
        </table>
    </div>
    {{end}}

    {{if .DDoSFindings}}
    <div class="section">
        <h2>⚠️ DDoS Findings</h2>
        <table>
            <tr><th>Type</th><th>Source IP</th><th>Target IP</th><th>Packet Count</th></tr>
            {{range .DDoSFindings}}
            <tr><td>{{.Type}}</td><td>{{.SourceIP}}</td><td>{{.TargetIP}}</td><td>{{.PacketCount}}</td></tr>
            {{end}}
        </table>
    </div>
    {{end}}

    {{if .TLSSecurityFindings}}
    <div class="section">
        <h2>🔐 TLS Security Issues</h2>
        <table>
            <tr><th>Server IP</th><th>Weakness Type</th><th>Severity</th><th>Description</th></tr>
            {{range .TLSSecurityFindings}}
            <tr><td>{{.ServerIP}}</td><td>{{.WeaknessType}}</td><td>{{.Severity}}</td><td>{{.Description}}</td></tr>
            {{end}}
        </table>
    </div>
    {{end}}

    <div class="section">
        <h2>ℹ️ Debug Info</h2>
        <p>This is a simplified debug report. For full analysis, use the standard HTML report.</p>
        <p>Report generated by SD-WAN Triage Tool</p>
    </div>
</body>
</html>`

	// Prepare template data
	type DebugData struct {
		PCAPFile               string
		Timestamp              string
		TotalBytes             uint64
		DNSAnomalyCount        int
		TCPRetransmissionCount int
		FailedHandshakeCount   int
		TLSCertCount           int
		ARPConflictCount       int
		HTTPErrorCount         int
		TrafficFlowCount       int
		DDoSCount              int
		PortScanCount          int
		IOCCount               int
		TLSSecurityCount       int
		ICMPCount              int
		TunnelCount            int
		SDWANVendorCount       int
		BGPIndicatorCount      int
		RiskScore              int
		RiskLevel              string
		TopIssue               string
		DNSAnomalies           []models.DNSAnomaly
		DDoSFindings           []models.DDoSFinding
		TLSSecurityFindings    []models.TLSSecurityFinding
	}

	// Limit DNS anomalies to first 20
	dnsAnomalies := report.DNSAnomalies
	if len(dnsAnomalies) > 20 {
		dnsAnomalies = dnsAnomalies[:20]
	}

	data := DebugData{
		PCAPFile:               pcapFile,
		Timestamp:              time.Now().Format("2006-01-02 15:04:05"),
		TotalBytes:             report.TotalBytes,
		DNSAnomalyCount:        len(report.DNSAnomalies),
		TCPRetransmissionCount: len(report.TCPRetransmissions),
		FailedHandshakeCount:   len(report.FailedHandshakes),
		TLSCertCount:           len(report.TLSCerts),
		ARPConflictCount:       len(report.ARPConflicts),
		HTTPErrorCount:         len(report.HTTPErrors),
		TrafficFlowCount:       len(report.TrafficAnalysis),
		DDoSCount:              len(report.Security.DDoSFindings),
		PortScanCount:          len(report.Security.PortScanFindings),
		IOCCount:               len(report.Security.IOCFindings),
		TLSSecurityCount:       len(report.Security.TLSSecurityFindings),
		ICMPCount:              len(report.ICMPAnalysis),
		TunnelCount:            len(report.TunnelAnalysis),
		SDWANVendorCount:       len(report.SDWANVendors),
		BGPIndicatorCount:      len(report.BGPHijackIndicators),
		RiskScore:              report.RiskScore,
		RiskLevel:              report.RiskLevel,
		TopIssue:               report.TopIssue,
		DNSAnomalies:           dnsAnomalies,
		DDoSFindings:           report.Security.DDoSFindings,
		TLSSecurityFindings:    report.Security.TLSSecurityFindings,
	}

	// Parse and execute template
	tmpl, err := template.New("debug").Parse(debugTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse debug template: %w", err)
	}

	file, err := os.Create(filename)
	if err != nil {
		return fmt.Errorf("failed to create debug HTML file: %w", err)
	}
	defer file.Close()

	if err := tmpl.Execute(file, data); err != nil {
		return fmt.Errorf("failed to execute debug template: %w", err)
	}

	return nil
}
