import React, { useState } from 'react';
import {
  BookOpen,
  ChevronDown,
  ChevronUp,
  Info,
  Shield,
  Lock,
  Ban,
  GitFork,
  CheckCircle,
  XCircle,
  AlertTriangle,
  Radio,
  Activity,
  Layers,
} from 'lucide-react';
import type { Discrepancy } from '../types';

// ─── Educational Legend (Collapsible) ─────────────────────────────

export const EducationalLegend: React.FC = () => {
  const [open, setOpen] = useState(false);

  const concepts = [
    {
      icon: <Shield className="w-5 h-5 text-blue-400" />,
      title: 'Path Integrity Score',
      color: 'border-blue-500/30',
      description:
        'The percentage of traffic that successfully traversed the SD-WAN device. ' +
        '90%+ is healthy. Below 80% suggests packet loss or blocking. ' +
        'The denominator excludes control plane traffic (BFD/OMP) and LAN-only noise (SNMP, broadcasts) ' +
        'so the score reflects only user data-plane health.',
    },
    {
      icon: <Lock className="w-5 h-5 text-cyan-400" />,
      title: 'Verified Encrypted Transit',
      color: 'border-cyan-500/30',
      description:
        'Traffic that passed through the tunnel securely. We cannot see the data inside ' +
        '(it\'s encrypted by ESP/DTLS), but time+size correlation proves it arrived on the WAN side ' +
        'within ±50ms with matching packet size (adjusted for tunnel overhead). ' +
        'These packets count as "successfully transited" in the score.',
    },
    {
      icon: <Ban className="w-5 h-5 text-red-400" />,
      title: 'Policy Drops',
      color: 'border-red-500/30',
      description:
        'A TCP connection attempt (SYN) was seen on the LAN but vanished on the WAN. ' +
        'This usually means a Firewall Rule, Zone-Based Firewall (ZBFW), or Access Control List (ACL) ' +
        'blocked it. Check the SD-WAN policy or edge firewall configuration. ' +
        'Look for "implicit deny" rules that might be catching legitimate traffic.',
    },
    {
      icon: <GitFork className="w-5 h-5 text-purple-400" />,
      title: 'Asymmetric Routing (MISSING_A)',
      color: 'border-purple-500/30',
      description:
        'Traffic seen on the WAN side that was never seen on the LAN side. ' +
        'This often means return traffic is bypassing the SD-WAN device or using a different path. ' +
        'Common causes: direct internet breakout, asymmetric ECMP, or traffic injected by a WAN peer. ' +
        'A small number is normal; a large number may indicate a routing loop or misconfigured path preference.',
    },
    {
      icon: <Radio className="w-5 h-5 text-slate-400" />,
      title: 'Control Plane Traffic',
      color: 'border-slate-500/30',
      description:
        'BFD keepalives, OMP updates, and DTLS control packets generated by the SD-WAN device itself. ' +
        'These will never appear in the LAN capture because they originate from the router, not from user endpoints. ' +
        'They are excluded from the Path Integrity Score denominator so they don\'t artificially lower the score.',
    },
    {
      icon: <AlertTriangle className="w-5 h-5 text-yellow-400" />,
      title: 'Noise Traffic (Excluded)',
      color: 'border-yellow-500/30',
      description:
        'LAN-side traffic that the SD-WAN device correctly does not forward to the WAN: ' +
        'broadcast/multicast, SNMP polling (UDP 161/162), Syslog (UDP 514), NTP (UDP 123), ' +
        'HSRP/VRRP, and same-subnet LAN chatter. These are excluded from the score denominator ' +
        'because they were never WAN candidates.',
    },
  ];

  return (
    <div className="bg-slate-800/60 border border-slate-700/50 rounded-xl overflow-hidden">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between px-5 py-3.5 hover:bg-slate-700/30 transition-colors"
      >
        <div className="flex items-center gap-2.5">
          <BookOpen className="w-4.5 h-4.5 text-blue-400" />
          <span className="text-sm font-medium text-slate-300">How to Read This Report</span>
          <span className="px-2 py-0.5 text-[10px] font-medium bg-blue-500/15 text-blue-400 rounded-full">
            Guide
          </span>
        </div>
        {open ? (
          <ChevronUp className="w-4 h-4 text-slate-500" />
        ) : (
          <ChevronDown className="w-4 h-4 text-slate-500" />
        )}
      </button>

      {open && (
        <div className="px-5 pb-5 border-t border-slate-700/30">
          <p className="text-xs text-slate-500 mt-3 mb-4">
            This report compares a LAN-side capture (before the SD-WAN device) with a WAN-side capture
            (after the device) to find where packets are dropped, modified, or injected.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {concepts.map((c) => (
              <div
                key={c.title}
                className={`bg-slate-900/50 border ${c.color} rounded-lg p-4`}
              >
                <div className="flex items-center gap-2 mb-2">
                  {c.icon}
                  <span className="text-sm font-semibold text-white">{c.title}</span>
                </div>
                <p className="text-xs text-slate-400 leading-relaxed">{c.description}</p>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

// ─── Info Tooltip ─────────────────────────────────────────────────

interface InfoTooltipProps {
  text: string;
}

export const InfoTooltip: React.FC<InfoTooltipProps> = ({ text }) => {
  return (
    <span className="relative group inline-flex items-center ml-1 cursor-help">
      <Info className="w-3.5 h-3.5 text-slate-500 group-hover:text-blue-400 transition-colors" />
      <span className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 px-3 py-2 text-[11px] leading-relaxed text-slate-200 bg-slate-900 border border-slate-600 rounded-lg shadow-xl opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none whitespace-normal w-64 z-50 text-center">
        {text}
        <span className="absolute top-full left-1/2 -translate-x-1/2 -mt-px border-4 border-transparent border-t-slate-600" />
      </span>
    </span>
  );
};

// ─── Metric Tooltip Definitions ───────────────────────────────────

export const METRIC_TOOLTIPS = {
  matched:
    'Packets found in both captures with matching IP headers, ports, and sequence numbers. These packets transited the SD-WAN device without modification.',
  dropped:
    'Packets that entered the LAN interface but never exited the WAN interface. The device dropped them — usually due to a firewall policy, ACL, or route blackhole.',
  modified:
    'Packets found in both captures but with changes to TTL, DSCP/QoS markings, or IP addresses (NAT). The packet transited but was altered by the device.',
  asymmetric:
    'Packets found on the WAN side but not on the LAN side. These were either injected by the device itself or arrived via a different routing path (asymmetric routing).',
  encrypted:
    'Tunnel packets where the inner payload is encrypted (ESP/DTLS). We correlated them by matching packet timestamps (±50ms) and sizes (adjusted for tunnel overhead).',
  controlPlane:
    'BFD, OMP, and keepalive packets generated by the router itself. These are excluded from the user traffic score because they will never have a LAN-side counterpart.',
  policyDrop:
    'TCP SYN packets seen on LAN but not WAN — a connection attempt was blocked. Check Zone-Based Firewall (ZBFW), ACL, or SD-WAN App-Aware policy.',
  blackhole:
    'Ongoing data flow that suddenly stops appearing on WAN. Could indicate a route withdrawal, interface flap, or MTU issue causing silent drops.',
  verifiedEncrypted:
    'Encrypted tunnel packets where time+size correlation confirms the LAN packet transited through the WAN tunnel. Counted as "successfully transited" in the score.',
  packetsA:
    'Total packets in the LAN-side capture (before the SD-WAN device). This is what the user endpoints sent into the network.',
  packetsB:
    'Total packets in the WAN-side capture (after the SD-WAN device). Includes user data, control plane, and tunnel overhead.',
  noiseTraffic:
    'LAN-side traffic correctly not forwarded to WAN: broadcasts, SNMP (UDP 161/162), Syslog (UDP 514), NTP (UDP 123), same-subnet chatter, and routing protocols.',
} as const;

// ─── Discrepancy Analysis ─────────────────────────────────────────

export function getDiscrepancyAnalysis(d: Discrepancy): {
  summary: string;
  suggestion: string;
  seniorTip: string;
  icon: React.ReactNode;
  severity: 'info' | 'warning' | 'critical';
} {
  // MISSING_B: Packet dropped by device
  if (d.state === 'MISSING_B') {
    // TCP SYN dropped → Firewall / ACL
    if (d.tcp_flags && d.tcp_flags.includes('SYN') && !d.tcp_flags.includes('ACK')) {
      return {
        summary: 'Firewall Block — TCP SYN dropped',
        suggestion:
          'A new connection attempt was blocked by the SD-WAN device. Check Zone-Based Firewall (ZBFW), ' +
          'Access Control Lists (ACL), or SD-WAN App-Aware routing policy. Look for "implicit deny" rules.',
        seniorTip: `Compare the source IP (${d.src_ip}) against your Firewall Rules. Is this IP allowed to talk to ${d.dst_ip}:${d.dst_port}? Check for ACLs on both LAN and WAN interfaces. If this traffic should be allowed, add an explicit permit rule.`,
        icon: <Ban className="w-3.5 h-3.5 text-red-400" />,
        severity: 'critical',
      };
    }
    // TCP RST → Connection reset
    if (d.tcp_flags && d.tcp_flags.includes('RST')) {
      return {
        summary: 'Connection Reset dropped',
        suggestion:
          'A TCP RST was seen on LAN but not forwarded to WAN. The device may be filtering resets ' +
          'or the connection was already terminated on the WAN side.',
        seniorTip: 'Check if TCP state tracking is enabled on the firewall. Some firewalls drop RST packets for connections they consider already closed. This is usually harmless but can cause connection cleanup delays.',
        icon: <XCircle className="w-3.5 h-3.5 text-red-400" />,
        severity: 'warning',
      };
    }
    // Large packet → possible MTU issue
    if (d.length > 1400) {
      return {
        summary: 'Large packet dropped — possible MTU issue',
        suggestion:
          `Packet size (${d.length}B) exceeds common tunnel MTU. Check interface MTU settings ` +
          'and ensure Path MTU Discovery (PMTUD) is working. Consider lowering the TCP MSS ' +
          'or adjusting the tunnel MTU (typically 1400–1460 bytes).',
        seniorTip: `Check the WAN interface MTU (should be 1500+) and tunnel MTU (should be 1400-1460). Also verify TCP MSS clamping is configured: "ip tcp adjust-mss 1360". If ICMP is blocked, PMTUD will fail and large packets will be silently dropped.`,
        icon: <AlertTriangle className="w-3.5 h-3.5 text-yellow-400" />,
        severity: 'critical',
      };
    }
    // UDP drop
    if (d.protocol === 'UDP') {
      return {
        summary: 'UDP packet dropped',
        suggestion:
          'A UDP packet was not forwarded. Common causes: Application-Aware policy blocking the app, ' +
          'port-based ACL, or the traffic was classified as unwanted. Check SD-WAN app-route policy.',
        seniorTip: `Check the App-Aware Routing policy for port ${d.dst_port}. Is this application classified and allowed? Also check for rate limiting or policing on the WAN interface that might be dropping UDP traffic during congestion.`,
        icon: <XCircle className="w-3.5 h-3.5 text-red-400" />,
        severity: 'warning',
      };
    }
    // TCP data drop
    if (d.protocol === 'TCP') {
      return {
        summary: 'TCP data packet dropped',
        suggestion:
          'An established TCP flow had packets dropped. This could indicate mid-flow policy enforcement, ' +
          'a route change, or buffer overflow on the device. Check interface utilization and QoS queues.',
        seniorTip: 'Check WAN interface utilization with "show interface <wan-if> | include rate". If near 100%, packets are being tail-dropped. Review QoS queue statistics to see which traffic class is being dropped. Also check for route flapping.',
        icon: <XCircle className="w-3.5 h-3.5 text-red-400" />,
        severity: 'warning',
      };
    }
    // Generic drop
    return {
      summary: 'Packet dropped by device',
      suggestion:
        'This packet entered the LAN interface but did not appear on the WAN interface. ' +
        'Check routing table, firewall rules, and interface status on the SD-WAN device.',
      seniorTip: `Verify there is a valid route to ${d.dst_ip} with "show ip route ${d.dst_ip}". Check WAN interface status with "show interface <wan-if>". Review recent configuration changes that might have affected routing or firewall rules.`,
      icon: <XCircle className="w-3.5 h-3.5 text-red-400" />,
      severity: 'warning',
    };
  }

  // MISSING_A: Asymmetric / injected
  if (d.state === 'MISSING_A') {
    if (d.encrypted) {
      return {
        summary: 'Encrypted tunnel control packet',
        suggestion:
          'An encrypted packet on the WAN with no LAN match. Likely a tunnel keepalive, ' +
          'BFD probe, or OMP update generated by the device itself. This is normal behavior.',
        seniorTip: 'This is expected. Control plane traffic (BFD, OMP, DTLS) maintains tunnel health. Verify with "show bfd summary" and "show sdwan omp peers". Healthy control plane is essential for SD-WAN operation.',
        icon: <Lock className="w-3.5 h-3.5 text-cyan-400" />,
        severity: 'info',
      };
    }
    if (d.protocol === 'ICMP' || d.protocol === 'ICMPv6') {
      return {
        summary: 'Device-generated ICMP',
        suggestion:
          'The SD-WAN device generated an ICMP packet (ping, traceroute, or unreachable). ' +
          'This is normal — devices probe WAN paths for SLA measurement.',
        seniorTip: 'SD-WAN devices continuously probe paths using ICMP to measure latency, jitter, and packet loss. Check SLA monitoring with "show sdwan policy sla-class". These probes drive intelligent path selection decisions.',
        icon: <Activity className="w-3.5 h-3.5 text-slate-400" />,
        severity: 'info',
      };
    }
    if (d.tunnel_type) {
      return {
        summary: `Asymmetric tunnel traffic (${d.tunnel_type})`,
        suggestion:
          'Traffic seen inside a WAN tunnel with no LAN-side origin. The remote site may have sent this ' +
          'through the tunnel, or it\'s traffic from another branch arriving via the SD-WAN fabric.',
        seniorTip: 'This is normal for SD-WAN fabric traffic. Check "show sdwan omp routes" to see routes from other branches. If the source IP is from another site, this is expected return traffic or inter-branch communication.',
        icon: <Layers className="w-3.5 h-3.5 text-purple-400" />,
        severity: 'info',
      };
    }
    return {
      summary: 'Asymmetric routing detected',
      suggestion:
        'This packet appeared on the WAN but not the LAN. Common causes: return traffic using a different ' +
        'path, direct internet breakout, or traffic injected by a WAN peer. A small number is normal.',
      seniorTip: 'Check if this is return traffic from a locally-originated flow. If the source IP is external (internet), verify your DIA (Direct Internet Access) policy. A small amount of asymmetric routing is normal, but large amounts may indicate a routing loop.',
      icon: <GitFork className="w-3.5 h-3.5 text-purple-400" />,
      severity: 'info',
    };
  }

  // MODIFIED: NAT / QoS / TTL change
  if (d.state === 'MODIFIED') {
    const changes = d.field_changes?.map(fc => fc.field).join(', ') || '';
    if (changes.includes('SrcIP') || changes.includes('DstIP')) {
      return {
        summary: 'NAT translation applied',
        suggestion:
          'The device applied Network Address Translation (NAT), changing the source or destination IP. ' +
          'This is expected for internet-bound traffic. Verify the NAT pool or DIA (Direct Internet Access) config.',
        seniorTip: 'Check NAT translations with "show ip nat translations". For internet-bound traffic, source IP should be translated to a public IP. For site-to-site traffic, NAT should not be applied unless explicitly configured for overlapping subnets.',
        icon: <AlertTriangle className="w-3.5 h-3.5 text-yellow-400" />,
        severity: 'info',
      };
    }
    if (changes.includes('DSCP')) {
      return {
        summary: 'QoS remarking applied',
        suggestion:
          'The DSCP value was changed, meaning the SD-WAN device applied a QoS policy. ' +
          'Verify the App-Aware routing policy is classifying traffic correctly.',
        seniorTip: 'Verify DSCP remarking matches your QoS design: voice should be EF (46), video AF41 (34), bulk data AF11 (10). Check with "show policy-map interface <wan-if>" and "show sdwan app-route stats".',
        icon: <AlertTriangle className="w-3.5 h-3.5 text-yellow-400" />,
        severity: 'info',
      };
    }
    if (changes.includes('TTL')) {
      return {
        summary: 'TTL decremented (normal routing)',
        suggestion:
          'The TTL was decremented, which is normal IP routing behavior. Each Layer 3 hop decreases TTL by 1.',
        seniorTip: 'TTL decrement is expected. Each Layer 3 device (router) decrements TTL by 1. If TTL reaches 0, the packet is dropped and an ICMP "Time Exceeded" is sent back. This prevents routing loops.',
        icon: <CheckCircle className="w-3.5 h-3.5 text-green-400" />,
        severity: 'info',
      };
    }
    return {
      summary: 'Packet modified in transit',
      suggestion:
        `Fields changed: ${changes || 'unknown'}. The SD-WAN device altered this packet. ` +
        'Check NAT, QoS, and header rewrite policies.',
      seniorTip: 'Review the specific field changes in the discrepancy detail. TTL changes are normal (each hop decrements by 1). NAT and DSCP changes should match your policy configuration. Unexpected changes may indicate misconfigured policies.',
      icon: <AlertTriangle className="w-3.5 h-3.5 text-yellow-400" />,
      severity: 'warning',
    };
  }

  return {
    summary: 'Packet present in both captures',
    suggestion: 'This packet was found in both LAN and WAN captures — successful transit.',
    seniorTip: 'This is normal behavior. The packet was forwarded correctly with no issues. No action required.',
    icon: <CheckCircle className="w-3.5 h-3.5 text-green-400" />,
    severity: 'info',
  };
}
